### PR TITLE
Adds CoC poster

### PR DESCRIPTION
**Pull request by rzo1**
Hi @Claudenw ,

as discussed via Slack, here is my poster.

Gruß
Richard

### CODE REVIEW

**Comment by Claudenw** [comment]
Added new poster

**Review by Claudenw — CHANGES_REQUESTED** [review]
Can you add a license statement?

See https://github.com/rzo1/apachecon-eu/blob/main/posters/Wildcard_Match_Search_Strategy_Poster.pdf for an example.  If you can not that is fine, just let me know.

**Comment by rzo1** [comment]
@Claudenw Added a license statement covering the text. Since no code is included, i omitted that part ;-)

**Comment by Claudenw** [comment]
Adding poster

**Pull request merged**
